# Generated by Django 5.2.3 on 2025-07-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='summary',
        ),
    ]
