# Generated by Django 5.2.3 on 2025-07-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_bio_profile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_still_studying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_still_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
