# Generated by Django 5.2.3 on 2025-08-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resumeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='analysis_report',
            field=models.FileField(blank=True, null=True, upload_to='analysis_reports/'),
        ),
    ]
