# Generated by Django 5.2.3 on 2025-08-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_resumeanalysis_analysis_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='ai_model',
            field=models.CharField(default='gpt-5-nano', max_length=100),
        ),
    ]
