# Generated by Django 5.2.3 on 2025-08-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_resumeanalysis_ai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='ai_model',
            field=models.CharField(choices=[('gpt-4.1-nano', 'GPT-4.1 nano'), ('gpt-5-nano', 'GPT-5 nano'), ('gpt-4o-mini', 'GPT-4o mini')], default='gpt-5-nano', max_length=100),
        ),
    ]
