# Generated by Django 5.2.3 on 2025-08-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_resumeanalysis_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
