# Generated by Django 5.2.3 on 2025-08-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_resumeanalysis_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='type',
            field=models.CharField(blank=True, choices=[('resume', 'Resume'), ('cover-letter', 'Cover Letter')], null=True),
        ),
    ]
